crop_descriptions = {
        'rice': "Rice is a staple food and a primary crop, known for its versatility and importance in many cuisines.",
        'maize': "Maize, also known as corn, is a widely cultivated crop used for food, livestock feed, and industrial products.",
        'chickpea': "Chickpea is a legume known for its high protein content and is used in various dishes and cuisines around the world.",
        'kidneybeans': "Kidney beans are a popular legume rich in nutrients and commonly used in salads, stews, and side dishes.",
        'pigeonpeas': "Pigeonpeas are a drought-resistant legume grown for food, forage, and soil improvement in various regions.",
        'mothbeans': "Moth beans are small drought-resistant legumes used in traditional Indian cuisine and are rich in protein.",
        'mungbean': "Mung beans are widely cultivated for their edible seeds, which are used in salads, soups, and curries.",
        'blackgram': "Black gram is a type of lentil widely consumed in South Asia, often used in curries and other dishes.",
        'lentil': "Lentils are nutritious legumes used in a variety of dishes worldwide, known for their high protein content.",
        'pomegranate': "Pomegranates are known for their juicy seeds and are consumed fresh or used in juices, salads, and desserts.",
        'banana': "Bananas are a popular tropical fruit with a rich nutrient profile, often eaten fresh or used in smoothies and desserts.",
        'mango': "Mangoes are a beloved tropical fruit famous for their sweet flavor and are enjoyed fresh, in juices, or as chutneys.",
        'grapes': "Grapes are cultivated for fresh consumption and used to produce wine, raisins, and various grape-derived products.",
        'watermelon': "Watermelon is a refreshing summer fruit known for its high water content and sweet taste.",
        'muskmelon': "Muskmelon, also known as cantaloupe, is a sweet and fragrant fruit enjoyed fresh or in fruit salads.",
        'apple': "Apples are one of the most widely cultivated and consumed fruits, known for their versatility and nutritional value.",
        'orange': "Oranges are a citrus fruit rich in vitamin C and are consumed fresh, as juice, or used in cooking.",
        'papaya': "Papaya is a tropical fruit with a sweet taste and numerous health benefits, often eaten fresh or in smoothies.",
        'coconut': "Coconuts are tropical fruits known for their versatile uses, including fresh consumption, coconut water, and oil.",
        'cotton': "Cotton is a major fiber crop used to produce textiles and various products, playing a vital role in the textile industry.",
        'jute': "Jute is a natural fiber used to make burlap and other textiles, commonly grown in regions with favorable climate.",
        'coffee': "Coffee beans are the seeds of the coffee plant and are used to produce the popular beverage enjoyed worldwide."
}