fertilizer_dict = {
    'rice': 'Zinc, Boron, Iron',
    'maize': 'Magnesium, Sulfur, Copper',
    'chickpea': 'Boron, Molybdenum, Calcium',
    'kidneybeans': 'Copper, Magnesium, Sulfur',
    'pigeonpeas': 'Manganese, Zinc, Calcium',
    'mothbeans': 'Molybdenum, Iron, Boron',
    'mungbean': 'Copper, Sulfur, Magnesium',
    'blackgram': 'Manganese, Zinc, Boron',
    'lentil': 'Molybdenum, Iron, Calcium',
    'pomegranate': 'Magnesium, Sulfur, Copper',
    'banana': 'Zinc, Boron, Manganese',
    'mango': 'Calcium, Sulfur, Iron',
    'grapes': 'Boron, Copper, Molybdenum',
    'watermelon': 'Magnesium, Zinc, Calcium',
    'muskmelon': 'Molybdenum, Iron, Boron',
    'apple': 'Sulfur, Magnesium, Copper',
    'orange': 'Zinc, Manganese, Calcium',
    'papaya': 'Copper, Sulfur, Magnesium',
    'coconut': 'Boron, Iron, Molybdenum',
    'cotton': 'Manganese, Zinc, Calcium',
    'jute': 'Molybdenum, Boron, Copper',
    'coffee': 'Sulfur, Magnesium, Zinc'
}
